import {
    Briefcase,
    Building2,
    DollarSign,
    FileText,
    Globe,
    Home,
    Layers,
    MessageCircle,
    Newspaper,
    Phone,
    UserCircle,
} from "lucide-react";

import { MenuItem } from "../types/sidebar";

export const editorWebsiteMenu: MenuItem[] = [
    {
        title: "website_content",
        isSection: true,
        permissions: [
            "view media",
            "manage site settings",
            "view social links",
            "view portfolio categories",
            "view portfolio items",
            "view clients",
            "view testimonials",
            "view pricing sections",
            "view pricing plans",
            "view service categories",
            "view service items",
            "view faqs",
            "view stat counters",
            "view page blocks",
            "view why choose items",
            "view about drive items",
            "view about objectives",
            "view blogs",
        ],
    },
    {
        title: "editor_overview",
        icon: Home,
        path: "/editor",
        permissions: [
            "view media",
            "manage site settings",
            "view social links",
            "view portfolio categories",
            "view portfolio items",
            "view clients",
            "view testimonials",
            "view pricing sections",
            "view pricing plans",
            "view service categories",
            "view service items",
            "view faqs",
            "view stat counters",
            "view page blocks",
            "view why choose items",
            "view about drive items",
            "view about objectives",
            "view blogs",
        ],
    },
    {
        title: "editor_site_wide",
        icon: Globe,
        path: "/editor/site-wide",
        permissions: ["manage site settings", "view social links", "view media"],
    },
    {
        title: "editor_home_page",
        icon: Home,
        path: "/editor/home",
        permissions: ["view page blocks", "view stat counters", "view clients", "view testimonials", "view why choose items"],
    },
    {
        title: "editor_about_page",
        icon: UserCircle,
        path: "/editor/about",
        permissions: ["view page blocks", "view about drive items", "view about objectives"],
    },
    {
        title: "services",
        icon: Layers,
        children: [
            {
                title: "editor_service_business_automation",
                path: "/editor/services/business-automation",
            },
            {
                title: "editor_service_business_presence",
                path: "/editor/services/business-presence",
            },
            {
                title: "editor_service_consulting",
                path: "/editor/services/consulting-analyzing",
            },
        ],
        permissions: ["view service categories", "view service items", "view faqs"],
    },
    {
        title: "pricing",
        icon: DollarSign,
        children: [
            {
                title: "editor_pricing_packages",
                path: "/editor/pricing",
            },
            {
                title: "editor_pricing_page",
                path: "/editor/pricing/page",
            },
        ],
        permissions: ["view pricing sections", "view pricing plans", "view page blocks"],
    },
    {
        title: "portfolio",
        icon: Briefcase,
        path: "/editor/portfolio",
        permissions: ["view portfolio categories", "view portfolio items"],
    },
    {
        title: "editor_clients_page",
        icon: Building2,
        path: "/editor/clients",
        permissions: ["view clients"],
    },
    {
        title: "editor_blog_page",
        icon: Newspaper,
        path: "/editor/blog",
        permissions: ["view blogs"],
    },
    {
        title: "editor_faq_page",
        icon: MessageCircle,
        path: "/editor/faq",
        permissions: ["view faqs"],
    },
    {
        title: "editor_contact_page",
        icon: Phone,
        path: "/editor/contact",
        permissions: ["view page blocks", "manage site settings"],
    },
];
